import { createElement } from '@lwc/engine-dom';
import AgentIsvOrgTypes from 'c/agentIsvOrgTypes';

describe('c-agent-isv-org-types', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-agent-isv-org-types', {
            is: AgentIsvOrgTypes
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});
